### ISSUE TITLE
What does "replace with the latest commit hash" mean?

### ISSUE THREAD

**Issue by lizyChy0329** [autofix-ci/action#18] opened 2024-08-30 10:12 UTC
What does "replace with the latest commit hash" mean? So, should I change the hash when the project updates every time?
```
- uses: autofix-ci/action@hash  # replace with the latest commit hash
```

I can see that Unocss use `- uses: autofix-ci/action@v1` also

**Comment by mhils** [comment] 2024-08-30 11:27
Duplicate of https://github.com/autofix-ci/action/issues/17#issuecomment-2236548431?

**Closed** 2024-09-04 02:15 UTC
